### ISSUE TITLE
Cookie cache not updated from auth.api.getSession (Tanstack-Start)

### ISSUE THREAD

**Issue by dannylin108** [better-auth/better-auth#4389]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

I see `session_data` cookie set after sign-in, but after it expires, subsequent successful calls of `auth.api.getSession` in server-function or middle-ware don't set the cookie again.

A workaround proposed the by the bot (https://github.com/better-auth/better-auth/discussions/4231) is to call `getSession({header, asRequest: true })` and then set the cookies manually:

```ts
// Use asResponse:true to ensure cookies are set by Better Auth
        const res = await auth?.api.getSession({ headers, asResponse: true });
        let data: Session | null = null;
        let user: SessionUser | null = null;
        if (res && res instanceof Response) {
            try {
                data = await res.json() as Session | null;
                user = data?.user ?? null;
            } catch {
                console.error('authRedirect> failed to parse session', res);
            }
            if (user) {
                applyResponseCookies(res);
            }
        }

// ----

function applyResponseCookies(res: Response) {
    const cookieList = res.headers.getSetCookie();

    if (!cookieList?.length) return;

    for (const cookieStr of cookieList) {
    // ....
       setCookie(name, value, opts);
    }
}
```

but it's kinda weird, plus before, I remember, it was working seamlessly. So it's a newly introduced bug.

### Current vs. Expected behavior

I expect that after one hour according to my settings, `auth.api.getSession` called from server function or middleware will set `session_data` cookie, but it doesn't happen.

### What version of Better Auth are you using?

1.3.7

### System info

```bash
System:
    OS: Linux 6.12 cpe:/o:nixos:nixos:25.05 25.05 (Warbler)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.43 GB / 15.32 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Browsers:
    Brave Browser: 139.1.81.136
    Chromium: 139.0.7258.154
```

### Which area(s) are affected? (Select all that apply)

Client, Backend

### Auth config (if applicable)

```typescript
export const auth = betterAuth({
    database: drizzleAdapter(getDb(), {
        provider: "sqlite",
        schema: {
            ...authSchema,
        },
        usePlural: true
    }),
    plugins: [
        tgAuthPlugin(),
        reactStartCookies()
    ],
    session: {
        cookieCache: {
            enabled: true,
            maxAge: 60 * 60 * 1 // 1 hour, will be updated in middleware
        },
        expiresIn: TEN_DAYS_IN_SECONDS, 
        updateAge: 60 * 60 * 24, // 1 day
    },

});
```

**Comment by broamapronaokiabe** [comment]
Maybe this update helps. [b5e3bdc4b058.zip](https://github.com/user-attachments/files/22121810/b5e3bdc4b058.zip)

**Comment by LonJonn** [comment]
The reactStartCookies() plugin doesn't work properly. I just copied it's source I swapped out the cookie set calls with the ones from tanstack start directly:

```ts
import { setCookie } from "@tanstack/react-start/server";
import { parseSetCookieHeader } from "better-auth/cookies";

function autoCookies(): BetterAuthPlugin {
  return {
    id: "auto-cookies",
    hooks: {
      after: [
        {
          matcher(_ctx) {
            return true;
          },
          handler: createAuthMiddleware(async (ctx) => {
            const returned = ctx.context.responseHeaders;
            if ("_flag" in ctx && ctx._flag === "router") {
              return;
            }
            if (returned instanceof Headers) {
              const setCookies = returned?.get("set-cookie");
              if (!setCookies) {
                return;
              }
              const parsed = parseSetCookieHeader(setCookies);
              parsed.forEach((value, key) => {
                if (!key) {
                  return;
                }
                const opts = {
                  sameSite: value.samesite,
                  secure: value.secure,
                  maxAge: value["max-age"],
                  httpOnly: value.httponly,
                  domain: value.domain,
                  path: value.path,
                };

                setCookie(key, decodeURIComponent(value.value), opts);
              });
              return;
            }
          }),
        },
      ],
    },
  };
}
```

And now you can use this in place of reactStartCookies()

**Comment by dannylin108** [comment]
@LonJonn , yes, that's the solution, thanks a lot!

**Comment by jsa4000** [comment]
@LonJonn awesome! that's works, now using all auth.api.*, etc.. work with cookies.

**Comment by Gallevy** [comment]
@LonJonn where is `createAuthMiddleware` imported from, its not available for me even if i install `@better-auth/core`

Edit: Found it, i was confused about the default branch which is canary which changed where it was located

**Comment by uriafranko** [comment]
for some reason I still get empty set-cookie also the parsed is empty 

List of plugins:
``` plugins: [
      lastLoginMethod(),
      organization(),
      apiKey({
        enableSessionForAPIKeys: true,
        apiKeyHeaders: ["x-api-key"],
        enableMetadata: true,
        rateLimit: {
          enabled: true,
          maxRequests: 100,
          timeWindow: 60 * 1000, // 1 minute
        },
      }),
      autoCookies(),
    ],
```

**Comment by dannylin108** [comment]
Seems fixed in 1.4+

**Comment by jsa4000** [comment]
Hi, @dannylin108. how do you make it work? In my case using newest versions from 1.4.X do not solve the problem at all and the cookie is not being set in the server. I am still using the code provided by @LonJonn 

Thanks in advance.

**Comment by jrdn91** [comment]
This still does not resolve the issue for me. I am on 1.4.10 of better-auth. Sessions are being created in my database, but no session token is being stored as a cookie in the browser, so I can't use any of the methods to get the session as there is no token to be referenced.

**Comment by jrdn91** [comment]
> This still does not resolve the issue for me. I am on 1.4.10 of better-auth. Sessions are being created in my database, but no session token is being stored as a cookie in the browser, so I can't use any of the methods to get the session as there is no token to be referenced.

I saw in the Better Auth discord a node from a user that Tan Stack needs node v22 and that they were on node v20 (I was in the same boat) and changing to node v22 fixed the isssue. I can confirm this has resolve the issue, and I can use the built in plugin. Here is the comment if you have joined the Better Auth discord

https://discord.com/channels/1288403910284935179/1460284624038006865/1460293179155939389

@jsa4000 thi might help you if you are still stuck on this

**Comment by nachomglz** [comment]
I'm a bit lost on this issue, I'm not using tanstack for anything, I have a next.js app and a separate fastify server holding the better auth server.

I have cookieCache enabled, and when I do `await getSession({ query: { disableCookieCache: true} })` from the server client (created using `better-auth/client`'s `crateAuthClient` method) it returns the updated session (the one in the database) but it doesn't refresh the cookie, but when I do the same call from a client component or from any other http client - it does refresh the cookie even for the calls from the server.

This is extremely confusing and I still don't really understand what the issue is.

Does this mean that we can't - at all - handle sessions on the server without relying on the client to refresh the cookies?
