### ISSUE TITLE
Failed to fetch dynamically imported module: node:async_hooks

### ISSUE THREAD

**Issue by qweered** [better-auth/better-auth#5539]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

I've updated from 1.3.27 to 1.3.29 and saw that error. toNextjsHandler configured correctly. I have proxy.ts file instead of middleware.ts. 1.3.27 with proxy.ts also works correctly, not tested 1.3.29 

```ts
export async function proxy(request: NextRequest) {
    const session = await auth.api.getSession({
        headers: await headers()
    })

    if (!session) {
        return NextResponse.redirect(new URL('/login', request.url))
    }

    return NextResponse.next()
}

export const config = {
    matcher: ['/dashboard', '/profile', '/settings', '/create-organization', '/invitations']
}
```

### Current vs. Expected behavior

Do not have error

```bash
 ✓ Ready in 3.4s
[browser] [better-auth] Warning: AsyncLocalStorage is not available in this environment. Some features may not work as expected. (file:///home/qweered/Projects/automaspec/.next/dev/static/chunks/02ec3_next_dist_91e776ba._.js:2294:13)
[browser] [better-auth] Please read more about this warning at https://better-auth.com/docs/installation#mount-handler (file:///home/qweered/Projects/automaspec/.next/dev/static/chunks/02ec3_next_dist_91e776ba._.js:2294:13)
[browser] [better-auth] If you are using Cloudflare Workers, please see: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag (file:///home/qweered/Projects/automaspec/.next/dev/static/chunks/02ec3_next_dist_91e776ba._.js:2294:13)
[browser] ⨯ unhandledRejection: TypeError: Failed to fetch dynamically imported module: node:async_hooks
TypeError: Failed to fetch dynamically imported module: node:async_hooks
```

### What version of Better Auth are you using?

1.3.29

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#1-NixOS SMP PREEMPT_DYNAMIC Wed Oct 15 10:04:23 UTC 2025",
    "release": "6.17.3-cachyos",
    "cpuCount": 8,
    "cpuModel": "AMD Ryzen 3 5300U with Radeon Graphics",
    "totalMemory": "14.95 GB",
    "freeMemory": "5.20 GB"
  },
  "node": {
    "version": "v22.19.0",
    "env": "development"
  },
  "packageManager": {
    "name": "pnpm",
    "version": "10.18.3"
  },
  "frameworks": [
    {
      "name": "next",
      "version": "16.0.0"
    },
    {
      "name": "react",
      "version": "19.2.0"
    }
  ],
  "databases": [
    {
      "name": "@libsql/client",
      "version": "^0.15.15"
    },
    {
      "name": "drizzle",
      "version": "^0.44.7"
    }
  ],
  "betterAuth": {
    "version": "1.3.27",
    "config": null
  }
}
```

### Which area(s) are affected? (Select all that apply)

Client

### Auth config (if applicable)

```typescript
export const auth = betterAuth({
    database: drizzleAdapter(db, {
        provider: 'sqlite',
        schema: schema
    }),
    trustedOrigins: [...(process.env.VERCEL_URL ? [`https://${process.env.VERCEL_URL}`] : [])],
    emailAndPassword: {
        enabled: true
    },
    plugins: [
        organization({
            allowUserToCreateOrganization: true,
            organizationLimit: 1,
            membershipLimit: 1,
            creatorRole: 'owner'
        })
    ]
})

export const authClient = createAuthClient({
    baseURL: typeof window !== 'undefined' ? window.location.origin : undefined,
    plugins: [
        organizationClient({
            schema: inferOrgAdditionalFields<typeof auth>()
        })
    ]
})
```

**Comment by qweered** [comment]
Fixed

**Comment by thedevdavid** [comment]
@qweered it's present in the latest beta `1.4.0-beta.25`

**Comment by soultellegend** [comment]
I'm still seeing this in `better-auth@1.4.1` in a standard Next.js App Router app (Next 15, Node 22, pnpm).

In my case it only happens when I add the Polar adapter client plugin:

```ts
import { createAuthClient } from "better-auth/react";
import { polarClient } from "@polar-sh/better-auth";

export const authClient = createAuthClient({
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000",
  plugins: [polarClient()],
});
```

As soon as this runs in the browser I get:

> Failed to fetch dynamically imported module: node:async_hooks

If I remove polarClient() from the plugins array, the error disappears and everything works as expected. No Cloudflare / edge runtime involved here  just a regular Node runtime with Express backend + Next.js frontend.


I’ve opened a related issue on the Polar adapters repo as well, and for now they suggested using the Polar SDK directly for embedded checkout as a workaround. That works for checkout, but it doesn’t cover the extra client methods shown in the Better Auth Polar docs (e.g. authClient.customer.orders.list, authClient.customer.benefits.list, etc.), which rely on the polarClient() plugin being usable on the frontend.


Edit: Yes client functions are working, only problem is console logs  Failed to fetch dynamically imported module: node:async_hooks

**Comment by rishi-raj-jain** [comment]
The code of polarClient is available at https://github.com/polarsource/polar-adapters/blob/main/packages/polar-betterauth/src/client.ts.

**Comment by rishi-raj-jain** [comment]
> from [this issue](https://github.com/polarsource/polar/issues/8002#issuecomment-3567941747)

The only issue with using polarClient is the console log error that shows up, the workaround shipped in [this PR](https://github.com/soultellegend/better-auth-polar-error/pull/1/files) does solve the issue and allows them to use the methods shown in the Better Auth Polar docs (e.g. authClient.customer.orders.list, authClient.customer.benefits.list, etc.) just fine.

**Comment by imqwertyc** [comment]
> Fixed

How??
@qweered

**Comment by qweered** [comment]
I suppose it was fixed #5555, i updated deps some time ago and error gone

**Comment by ijmozn** [comment]
> I suppose it was fixed #5555, i updated deps some time ago and error gone

It's still present for me in latest version 1.4.0

**Comment by shaked-frame** [comment]
also getting this after bumping to 1.4.1
any idea what causes it? seems like something is trying to cross the server-client boundary

**Comment by fcsouza** [comment]
anyone know how to resolve this error?
version "better-auth": "1.3.33", with the same error

Failed to fetch dynamically imported module: node:async_hooks

**Comment by batpool** [comment]
> anyone know how to resolve this error? version "better-auth": "1.3.33", with the same error
> 
> Failed to fetch dynamically imported module: node:async_hooks

same with as well 
```js
"better-auth": "^1.4.2",
```

<img width="677" height="42" alt="Image" src="https://github.com/user-attachments/assets/45e01b6c-a067-4cbd-aa08-a04ff2ff90a7" />

**Comment by maytees** [comment]
I'm getting the same error here.

**Comment by batpool** [comment]
i am getting the error after adding fofopayments

```ts
import { dodopaymentsClient } from "@dodopayments/better-auth";

export const authClient = createAuthClient({
  baseURL: process.env.BETTER_AUTH_URL || "http://localhost:3000",
  plugins: [dodopaymentsClient()],
});
```

**Comment by batpool** [comment]
https://github.com/better-auth/better-auth/blob/canary/packages/core/src/async_hooks/index.ts

here its not checking for browser or not, it should be skipped in browser

**Comment by landoncolburn** [comment]
I'm also getting this issue when using the polarClient plugin:


```typescript
import { polarClient } from "@polar-sh/better-auth";
import { createAuthClient } from "better-auth/react";
export const authClient = createAuthClient({
	baseURL: process.env.NEXT_PUBLIC_APP_URL,
	plugins: [polarClient()],
});
```

When I comment out the polarClient lines, the error goes away.

I've attached my console logs below from the browser:

```
[Error] Failed to load resource: unsupported URL (node:async_hooks, line 0)
[Warning] [better-auth] Warning: AsyncLocalStorage is not available in this environment. Some features may not work as expected. (7ae12_next_dist_e6700ec0._.js, line 2288)
[Warning] [better-auth] Please read more about this warning at https://better-auth.com/docs/installation#mount-handler (7ae12_next_dist_e6700ec0._.js, line 2288)
[Warning] [better-auth] If you are using Cloudflare Workers, please see: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag (7ae12_next_dist_e6700ec0._.js, line 2288)
[Error] Unhandled Promise Rejection: TypeError: Importing a module script failed.
	(anonymous function) (1ae26_@better-auth_core_dist_2ead24dc._.js:99)
```

This is running locally with node 22.17.0, next 16.0.4, @polar-sh/better-auth ^1.5.0, better-auth 1.4.2 and chrome 142.0.7444.176

**Comment by batpool** [comment]
> I'm also getting this issue when using the polarClient plugin:
> 
> import { polarClient } from "@polar-sh/better-auth";
> import { createAuthClient } from "better-auth/react";
> export const authClient = createAuthClient({
> 	baseURL: process.env.NEXT_PUBLIC_APP_URL,
> 	plugins: [polarClient()],
> });
> When I comment out the polarClient lines, the error goes away.
> 
> I've attached my console logs below from the browser:
> 
> ```
> [Error] Failed to load resource: unsupported URL (node:async_hooks, line 0)
> [Warning] [better-auth] Warning: AsyncLocalStorage is not available in this environment. Some features may not work as expected. (7ae12_next_dist_e6700ec0._.js, line 2288)
> [Warning] [better-auth] Please read more about this warning at https://better-auth.com/docs/installation#mount-handler (7ae12_next_dist_e6700ec0._.js, line 2288)
> [Warning] [better-auth] If you are using Cloudflare Workers, please see: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag (7ae12_next_dist_e6700ec0._.js, line 2288)
> [Error] Unhandled Promise Rejection: TypeError: Importing a module script failed.
> 	(anonymous function) (1ae26_@better-auth_core_dist_2ead24dc._.js:99)
> ```
> 
> This is running locally with node 22.17.0, next 16.0.4, @polar-sh/better-auth ^1.5.0, better-auth 1.4.2 and chrome 142.0.7444.176

i dont think this issue is noticed, we have to patch it manually, i have the patch but if its get fixed by the better auth team it will be good

**Comment by M4tT3d** [comment]
I have the same problem on my next project with a custom plugin developed by me. I tried both nextjs 15 and 16 with app router but without solutions. The problem is related to the imports from `better-auth/api`. I'm using better-auth@1.4.3
Folder structure:
- the server plugin is in `src/lib/custom-auth/index.ts`
- the client plugin is in `src/lib/custom-auth/client.ts`
- `auth.ts` is in the root of the project
- there are two hooks in `src/lib/custom-auth/hooks/`

**Comment by fugisakimatheus** [comment]
I'm having the same problem in my Next.js (v16) project, considering i only use the client because the back-end is in another project. The only places i use getSession are via the client, `client.getSession()` and this same error occurs:

- I using `better-auth@1.4.3`

```
Failed to fetch dynamically imported module: node:async_hooks
```

See the browser errors print:
<img width="761" height="223" alt="Image" src="https://github.com/user-attachments/assets/5568100d-3bbd-4377-8046-f630d4ed0960" />

I don't know if it could be related to something else as well.

_**Observation:** Even after disabling the `turbopack`, the error persists._

**Comment by dennisjnnh** [comment]
> https://github.com/better-auth/better-auth/blob/canary/packages/core/src/async_hooks/index.ts
> 
> here its not checking for browser or not, it should be skipped in browser

i have the same issue where the browser tries to import node:async_hooks. updated to 1.4.3

**Comment by imqwertyc** [comment]
I found a temporary solution for `polarClient`
use this plugin in your code as plugin: 
```ts
import type { CheckoutParams, polar } from "@polar-sh/better-auth";
import { PolarEmbedCheckout } from "@polar-sh/checkout/embed";
import type { BetterAuthClientPlugin } from "better-auth";
import type { BetterFetchOption } from "better-auth/client";

export const polarClient = () => {
	return {
		id: "polar-client",
		$InferServerPlugin: {} as ReturnType<typeof polar>,
		getActions: ($fetch) => {
			return {
				checkoutEmbed: async (
					data: Omit<CheckoutParams, "redirect" | "embedOrigin">,
					fetchOptions?: BetterFetchOption,
				) => {
					const res = await $fetch("/checkout", {
						method: "POST",
						body: {
							...data,
							redirect: false,
							embedOrigin: window.location.origin,
						},
						...fetchOptions,
					});

					if (res.error) {
						throw new Error(res.error.message);
					}

					const checkout = res.data as { url: string };

					const theme =
						(new URL(checkout.url).searchParams.get("theme") as
							| "light"
							| "dark"
							| undefined) ?? "light";

					return await PolarEmbedCheckout.create(checkout.url, theme);
				},
			};
		},
	} satisfies BetterAuthClientPlugin;
};
```
this is the exact copy of polar's implementation and it works for me and the error disappears.
I don't know how this works, but it works.
Maybe polar has some problems with their imports.

**Comment by rust0258** [comment]
still the same issue with v1.4.3

<img width="1598" height="512" alt="Image" src="https://github.com/user-attachments/assets/ade2c675-ae59-413f-84f6-9a02afd8bc9a" />

**Comment by landoncolburn** [comment]
I have a fix in the works, waiting on approvals

**Comment by nxtvoid** [comment]
issue with `polarClient()`

https://github.com/polarsource/polar/issues/8166#issue-3677158290

**Comment by pieterbeulque** [comment]
Hey, Pieter from Polar checking in here.

From my debugging, what's happening is that our build starts to include a file that tries to `import('node:async_hooks')` when we use `$InferServerPlugin: {} as ReturnType<typeof polarPlugin>`.

`node:async_hooks` is only imported in Better Auth's `test-utils` file, so I don't really understand why this file would make it into a production build of the package. That's what I'm trying to figure out now so we can fix the issue in our client too.

I haven't found any other workaround yet, i.e. the `$InferServerPlugin` _has_ to bridge from server-side code to client-side code, but in type-only world, so it should be doable.

**Comment by naodya** [comment]
I also created [this issue](https://github.com/polarsource/polar/issues/8251) with some details and a workaround that worked for me:

```TypeScript
import { PolarEmbedCheckout } from "@polar-sh/checkout/embed";

export const polarClient = () => ({
  id: "polar-client",
  $InferServerPlugin: {},
  getActions: ($fetch) => ({
    checkoutEmbed: async (data) => {
      const res = await $fetch("/checkout", {
        method: "POST",
        body: { ...data, redirect: false, embedOrigin: window.location.origin },
      });
      if (res.error) throw new Error(res.error.message);
      const theme = new URL(res.data.url).searchParams.get("theme") ?? "light";
      return await PolarEmbedCheckout.create(res.data.url, theme);
    },
  }),
});
```

**Comment by ijmozn** [comment]
@landoncolburn @Bekacru 
I update to tag `1.4.6-beta.3` which has the merged PR, I end up with Next JS (16.0.7 Turbopack) build error: 
`Code generation for chunk item errored`, I reverted back to 1.4.5 but still `node:async_hooks` issue 

> 
>  ⨯ ./node_modules/better-auth/dist/chunk-DieNfLhd.mjs
> An error occurred while generating the chunk item [project]/node_modules/better-auth/dist/chunk-DieNfLhd.mjs [app-client] (ecmascript)
> 
> Caused by:
> - the chunking context (unknown) does not support external modules (request: node:module)
> 
> Debug info:
> - An error occurred while generating the chunk item [project]/node_modules/better-auth/dist/chunk-DieNfLhd.mjs [app-client] (ecmascript)
> - Execution of <ModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
> - Execution of *EcmascriptChunkItemContent::new failed
> - Execution of EcmascriptModuleContent::new failed
> - the chunking context (unknown) does not support external modules (request: node:module)
> 
> Import traces:
>   Client Component Browser:
>     ./node_modules/better-auth/dist/chunk-DieNfLhd.mjs [Client Component Browser]
>     ./node_modules/better-auth/dist/get-migration--xV8I5XU.mjs [Client Component Browser]
>     ./node_modules/better-auth/dist/api/index.mjs [Client Component Browser]
>     ./node_modules/better-auth-credentials-plugin/dist/src/credentials/index.js [Client Component Browser]
>     ./node_modules/better-auth-credentials-plugin/dist/index.js [Client Component Browser]
>     ./src/lib/auth-client.ts [Client Component Browser]
>     ./src/app/auth/actions.ts [Client Component Browser]
>     ./src/components/auth/signin-form.tsx [Client Component Browser]
>     ./src/app/auth/sign-in/page.tsx [Client Component Browser]
>     ./src/app/auth/sign-in/page.tsx [Server Component]
> 
>   Client Component SSR:
>     ./node_modules/better-auth/dist/chunk-DieNfLhd.mjs [Client Component SSR]
>     ./node_modules/better-auth/dist/get-migration--xV8I5XU.mjs [Client Component SSR]
>     ./node_modules/better-auth/dist/api/index.mjs [Client Component SSR]
>     ./node_modules/better-auth-credentials-plugin/dist/src/credentials/index.js [Client Component SSR]
>     ./node_modules/better-auth-credentials-plugin/dist/index.js [Client Component SSR]
>     ./src/lib/auth-client.ts [Client Component SSR]
>     ./src/app/auth/actions.ts [Client Component SSR]
>     ./src/components/auth/signin-form.tsx [Client Component SSR]
>     ./src/app/auth/sign-in/page.tsx [Client Component SSR]
>     ./src/app/auth/sign-in/page.tsx [Server Component]
>

**Comment by landoncolburn** [comment]
I will try and reproduce this later, but at first glance it looks unrelated. Another issue from the co-bundling of client/server bundles though.

**Comment by landoncolburn** [comment]
@ibrahimjel I was not able to reproduce this with the following configuration:

```jsonc
// package.json
// ...
"dependencies": {
	"better-auth": "1.4.6-beta.3",
	"next": "16.0.7",
	"react": "19.2.1",
	"react-dom": "19.2.1"
},
// ...
```

```ts
// auth.ts
import { betterAuth } from "better-auth";

export const auth = betterAuth({
	emailAndPassword: {
		enabled: true,
	},
});
```

```ts
// auth-client.ts
import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
	baseURL: "http://localhost:3000",
});
```

Output from `next build`:
```
> next build

   ▲ Next.js 16.0.6 (Turbopack)
   - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully in 1393.6ms
 ✓ Finished TypeScript in 1681.9ms    
 ✓ Collecting page data using 11 workers in 248.4ms    
 ✓ Generating static pages using 11 workers (4/4) in 270.0ms
 ✓ Finalizing page optimization in 8.0ms    

Route (app)
┌ ○ /
├ ○ /_not-found
└ ƒ /api/auth/[...all]


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```

If you're still encountering this issue please provide me with a reproducible example, and maybe open a new issue? Thank you!

**Comment by Re4GD** [comment]
@landoncolburn twoFactorClient() is causing the issue for me 

---

Edit: just realized, I was importing from `better-auth/plugins`, not `better-auth/client/plugins`

```ts
import {
  adminClient,
  inferAdditionalFields,
  lastLoginMethodClient,
  usernameClient,
} from "better-auth/client/plugins";
import { twoFactorClient } from "better-auth/plugins";
import { createAuthClient } from "better-auth/react";
```

When I moved the import to the top it went away. Why is `better-auth/plugins` exporting client plugins anyway?

**Comment by landoncolburn** [comment]
@Re4GD Good catch, for some reason the twoFactor plugin is re-exporting all of its client functions. 

The line in question is here https://github.com/better-auth/better-auth/blob/9de80b35d8ff4aac88173450231279d2d7e62048/packages/better-auth/src/plugins/two-factor/index.ts#L118

These two tests will need to be updated as well:

https://github.com/better-auth/better-auth/blob/938c2a7c31fe6373fe63bce7368b0de725d911d8/packages/better-auth/src/plugins/two-factor/two-factor.test.ts#L9

https://github.com/better-auth/better-auth/blob/57ee11a26fd0d23d5504ba0c6e41631a4fa895f5/packages/better-auth/src/plugins/additional-fields/additional-fields.test.ts#L5

I can make the change to remove the export, but it will be a breaking change if anyone is already using the incorrect path (as the two test cases were).

@Bekacru are you able to give any insight into why the client functions are being exported in this file? 

This discussion should really be moved to a new issue though, as it's unrelated to async_hooks.

**Comment by mvriu5** [comment]
@ibrahimjel using a util method was the problem for me.
I changed the import from 
`import {capitalizeFirstLetter} from "@better-auth"`
to
`import {capitalizeFirstLetter} from "@better-auth/core/utils"`

**Comment by 0-Sandy** [comment]
I had the same error with my own plugin. In my case, the issue was that I was **re-exporting the client from the plugin’s `index.ts`**:

```ts
export { clientPlugin } from "./client";
```
And then importing it like this:
```ts
import { clientPlugin } from "./plugin";
```
The fix was to **import the client directly from its actual file**, without going through the re-export:
```ts
import { clientPlugin } from "./plugin/client";
```

I'm not sure if the Polar issue is fixed, but it's probably the same root cause. You just need to find where the client is defined and import it directly instead of relying on a re-export.

**Comment by troygoode** [comment]
You guys were able to put me on the right track as well. I was exporting a server plug and client plugin from the same field; splitting it fixed this issue for me. My original file was this:

```typescript
import { organizationClient as organizationClientPlugin } from "better-auth/client/plugins";
import { organization as organizationPlugin } from "better-auth/plugins";

export function organization() {
  return organizationPlugin({
    allowUserToCreateOrganization: async (_user) => {
      return true;
    },
  });
}

export function organizationClient() {
  return organizationClientPlugin({
    //
  });
}
```

I split it into 2 files:

```typescript
// server plugin

import { organization as organizationPlugin } from "better-auth/plugins";

export function organization() {
  return organizationPlugin({
    allowUserToCreateOrganization: async (_user) => {
      return true;
    },
  });
}
```

```typescript
// client plugin

import { organizationClient as organizationClientPlugin } from "better-auth/client/plugins";

export function organizationClient() {
  return organizationClientPlugin({
    //
  });
}
```

**Comment by dennisjnnh** [comment]
> [@landoncolburn](https://github.com/landoncolburn) twoFactorClient() is causing the issue for me
> 
> Edit: just realized, I was importing from `better-auth/plugins`, not `better-auth/client/plugins`
> 
> import {
>   adminClient,
>   inferAdditionalFields,
>   lastLoginMethodClient,
>   usernameClient,
> } from "better-auth/client/plugins";
> import { twoFactorClient } from "better-auth/plugins";
> import { createAuthClient } from "better-auth/react";
> When I moved the import to the top it went away. Why is `better-auth/plugins` exporting client plugins anyway?

This was the fix for async_hooks import on the client in my case.

**Comment by CleverSource** [comment]
@landoncolburn I am experiencing this same problem with the bundler. Using the admin plugin with this recommended [setup](https://www.better-auth.com/docs/plugins/admin#access-control). 

If you try to import:
```ts
import { createAccessControl } from "better-auth/plugins";
import { adminAc, defaultStatements } from "better-auth/plugins/admin/access";
```

and then import the file using those imports (e.g. your `permissions.ts` file) into the client for type-safety:
```ts
export const authClient = createAuthClient({
  baseURL: `${getBaseUrl()}/api/auth`,
  plugins: [
    adminClient({
      ac,
      roles: {
        admin,
      },
    }),
  ],
});
```

Bundler issues will occur. Is there a way to fix this without losing type-safety?

**Comment by 0-Sandy** [comment]
> @landoncolburn I am experiencing this same problem with the bundler. Using the admin plugin with this recommended [setup](https://www.better-auth.com/docs/plugins/admin#access-control). 
> 
> If you try to import:
> ```ts
> import { createAccessControl } from "better-auth/plugins";
> import { adminAc, defaultStatements } from "better-auth/plugins/admin/access";
> ```
> 
> and then import the file using those imports (e.g. your `permissions.ts` file) into the client for type-safety:
> ```ts
> export const authClient = createAuthClient({
>   baseURL: `${getBaseUrl()}/api/auth`,
>   plugins: [
>     adminClient({
>       ac,
>       roles: {
>         admin,
>       },
>     }),
>   ],
> });
> ```
> 
> Bundler issues will occur. Is there a way to fix this without losing type-safety?

It looks like the issue comes from importing `createAccessControl` from the wrong module.
In your code you have:

```ts
import { createAccessControl } from "better-auth/plugins";
```

However, according to the Better Auth docs, it should be imported from the **access plugin**:

```ts
import { createAccessControl } from "better-auth/plugins/access";
```

Docs reference: https://www.better-auth.com/docs/plugins/admin#create-access-control

**Comment by CleverSource** [comment]
> > @landoncolburn I am experiencing this same problem with the bundler. Using the admin plugin with this recommended [setup](https://www.better-auth.com/docs/plugins/admin#access-control). 
> > 
> > If you try to import:
> > ```ts
> > import { createAccessControl } from "better-auth/plugins";
> > import { adminAc, defaultStatements } from "better-auth/plugins/admin/access";
> > ```
> > 
> > and then import the file using those imports (e.g. your `permissions.ts` file) into the client for type-safety:
> > ```ts
> > export const authClient = createAuthClient({
> >   baseURL: `${getBaseUrl()}/api/auth`,
> >   plugins: [
> >     adminClient({
> >       ac,
> >       roles: {
> >         admin,
> >       },
> >     }),
> >   ],
> > });
> > ```
> > 
> > Bundler issues will occur. Is there a way to fix this without losing type-safety?
> 
> It looks like the issue comes from importing `createAccessControl` from the wrong module.
> In your code you have:
> 
> ```ts
> import { createAccessControl } from "better-auth/plugins";
> ```
> 
> However, according to the Better Auth docs, it should be imported from the **access plugin**:
> 
> ```ts
> import { createAccessControl } from "better-auth/plugins/access";
> ```
> 
> Docs reference: https://www.better-auth.com/docs/plugins/admin#create-access-control

This fixed it! Thanks for pointing that out

**Comment by aleksa-codes** [comment]
> I'm still seeing this in `better-auth@1.4.1` in a standard Next.js App Router app (Next 15, Node 22, pnpm).
> 
> In my case it only happens when I add the Polar adapter client plugin:
> 
> import { createAuthClient } from "better-auth/react";
> import { polarClient } from "@polar-sh/better-auth";
> 
> export const authClient = createAuthClient({
>   baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000",
>   plugins: [polarClient()],
> });
> As soon as this runs in the browser I get:
> 
> > Failed to fetch dynamically imported module: node:async_hooks
> 
> If I remove polarClient() from the plugins array, the error disappears and everything works as expected. No Cloudflare / edge runtime involved here just a regular Node runtime with Express backend + Next.js frontend.
> 
> I’ve opened a related issue on the Polar adapters repo as well, and for now they suggested using the Polar SDK directly for embedded checkout as a workaround. That works for checkout, but it doesn’t cover the extra client methods shown in the Better Auth Polar docs (e.g. authClient.customer.orders.list, authClient.customer.benefits.list, etc.), which rely on the polarClient() plugin being usable on the frontend.
> 
> Edit: Yes client functions are working, only problem is console logs Failed to fetch dynamically imported module: node:async_hooks

@ibrahimjel 
switching from:
```ts
import { polarClient } from "@polar-sh/better-auth";
```
to
```ts
import { polarClient } from "@polar-sh/better-auth/client"
```

Solved it for me. Both Polar and Better Auth docs still say to use `"@polar-sh/better-auth"` tho

**Comment by thewh1teagle** [comment]
Strangely when providing `polarClient()` from `@polar-sh/better-auth/client` to `createAuthClient(...)` it shows typescript errors.


Related

- https://github.com/polarsource/polar-adapters/issues/336
- https://github.com/polarsource/polar-adapters/issues/292

**Comment by aleksa-codes** [comment]
> Strangely when providing `polarClient()` from `@polar-sh/better-auth/client` to `createAuthClient(...)` it shows typescript errors.
> 
> Related
> 
> * [polarClient import breaks Next.js 16 Turbopack: node:async_hooks not available in browser polarsource/polar-adapters#336](https://github.com/polarsource/polar-adapters/issues/336)
> * [Polar + Better Auth Causes inferred type errors polarsource/polar-adapters#292](https://github.com/polarsource/polar-adapters/issues/292)

Looks like it got solved in `"better-auth": "^1.4.7"` importing from `"@polar-sh/better-auth"` works as expected now and builds successfully,
