### ISSUE TITLE
Systemic type issues across better-* packages ("cannot be named without a reference") (proposed parent issue)

### ISSUE THREAD

**Issue by firxworx** [better-auth/better-auth#5666]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

better-auth has systemic issues that repeat and reoccur version-after-version regarding the web of types and interdependencies between various `better-*` packages.

These packages are interdependent on different versions of each other and some types rely on internal types that are not consistently exported or have a consistent source of truth especially between versions.

Type issues are especially common in monorepos and with rigorous package managers like pnpm.

Ultimately type issues make better-auth a time-sink to incorporate into many projects and it can block good development practices at times. Clearly huge numbers of developers are impacted.

The common pattern is: `The inferred type of ... cannot be named without a reference to '...'`  and `This is likely not portable. A type annotation is necessary.ts(2742)`.

These appear to have common causes and they are entirely fixable. Workarounds should **not** involve telling devs to use TypeScript escape hatches like `as` casts.

Here are some issues I was able to find. I'm sure there are many more that are closed.

- https://github.com/better-auth/better-auth/issues/2123#issuecomment-3457437942 (read the comments this issue is absolutely not closed)
- https://github.com/better-auth/better-auth/issues/5637
- https://github.com/better-auth/better-auth/issues/5122
- https://github.com/better-auth/better-auth/issues/4250
- https://github.com/better-auth/better-auth/issues/2036

In issue #2142 I added a comment with a workaround here for those using drizzle adapter: 

https://github.com/better-auth/better-auth/issues/2123#issuecomment-3464227691

I comment on the "web" of interdependent types and give an example: 

`.pnpm/@better-auth+core@1.3.31_@better-auth+utils@0.3.0_@better-fetch+fetch@1.1.18_better-cal_1c46b965734ebfdf948befe6543bce20/node_modules/@better-auth/core/db/adapter`

---

Suggestions for devs:

**config helper**

Many libraries (vitest, eslint, hono (defineMiddleware()), etc.) offer a sort of `defineConfig()` function to help check both the config object argument _and_ guarantee that the return value is a particular **exportable** type with fixed source(s) of truth.

This can be used as a mechanism to help gloss over some of the deeper internal issues.

Such a helper could even add more value in future: e.g. a layer of validation and perhaps even checks that throw if something really bad or insecure is detected. 

### Current vs. Expected behavior

better-auth should work the way its supposed to and deliver on the promise of being TypeScript first and delivering type safety; better-auth types should support monorepos and having auth defined in a separate package.

### What version of Better Auth are you using?

1.3.34

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025",
    "release": "6.6.87.2-microsoft-standard-WSL2",
    "cpuCount": 0,
    "cpuModel": "XXX",
    "totalMemory": "X GB",
    "freeMemory": "X GB"
  },
  "node": {
    "version": "v22.13.1",
    "env": "development"
  },
  "packageManager": {
    "name": "pnpm",
    "version": "10.20.0"
  },
  "frameworks": null,
  "databases": null,
  "betterAuth": {
    "version": "Unknown",
    "config": null
  }
}
```

### Which area(s) are affected? (Select all that apply)

Types

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"
export const auth = betterAuth({
  emailAndPassword: {  
    enabled: true
  },
});
```

**Comment by firxworx** [comment]
Regarding some internal types getting out I wonder aloud if currying plays a factor. Its a fine practice but beware of how types can come along for the ride with the signature.

For example when investigating issue with the Drizzle adapter and `DBAdapter` type I saw:

```ts
declare const drizzleAdapter: (db: DB, config: DrizzleAdapterConfig) => (options: BetterAuthOptions) => DBAdapter<BetterAuthOptions>;
```

And type disagreements just so happen to be related to what `DBAdapter` and `BetterAuthOptions` are between packages.

**Comment by quirm** [comment]
Type generics in the lib are breaking based on various props. I had the same issue with this config:
```typescript
export const auth = (env: Env, db: DrizzleD1Database) => {
  return betterAuth({
    database: drizzleAdapter(db, {
      provider: 'sqlite',
      usePlural: true,
      schema
    }),
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET
  });
};
```
This issue was the presence of `drizzleAdapter`, luckily, [v1.3.34](https://github.com/better-auth/better-auth/releases/tag/v1.3.34) update fixed the issue.

Now, there is another type of problem when I include `mapProfileToUser`, e.g. 
```typescript
export const auth = (env: Env, db: DrizzleD1Database) => {
  return betterAuth({
    database: drizzleAdapter(db, {
      provider: 'sqlite',
      usePlural: true,
      schema
    }),
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    socialProviders: {
      discord: {
        clientId: env.DISCORD_CLIENT_ID,
        clientSecret: env.DISCORD_CLIENT_SECRET,
        disableDefaultScope: true,
        scope: ['identify'],
        mapProfileToUser: async (profile) => {
          return {
            email: profile.id + '@discord-id.com'
          };
        }
      }
    },
  });
};
```
If I remove `mapProfileToUser`, the problem is gone which I can't do because I need it. Is there a workaround, perhaps to fake some `mapProfileToUser` return type to avoid the TS error?

**updated**

So it seems this type override silences the error (`any` for the argument):
```typescript
mapProfileToUser: async (profile: any) => {
  return {
    email: profile.id + '@discord-id.com'
  };
}
```

**Comment by firxworx** [comment]
@quirm its not fixed with better-auth 1.3.34 but I was able to use an inline config very recently when I bumped its dependency better-call to latest 1.0.26 (I declare it as an explicit dependency).

I am not sure if this impacts mapProfileToUser though. 

I still suspect the core problem is the constantly in-flux interdependencies amongst `better-*` packages of different (and ever changing) version numbers that don't appear to have consistent type exports nor consistent [sources of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) (wiki) between them.

That's why I think this is a systemic issue that can frustratingly disappear and reappear between different versions of better-auth and/or one or more of its dependencies and it can feel almost random about what feature/plugin of better-auth is impacted.

**Comment by himself65** [comment]
I think we have fixed this in 1.4. So I'm closing. feel free to open a new type issue for 1.4

**Comment by chandlj** [comment]
@himself65 I'm also still getting this on v1.4-beta.21, so I definitely don't think it's fixed

**Comment by sanny-io** [comment]
I solved this issue by directly installing into my project whatever packages appeared in the error messages. @firxworx also touched on this point.

In the case of this error message:

`.pnpm/@better-auth+core@1.3.31_@better-auth+utils@0.3.0_@better-fetch+fetch@1.1.18_better-cal_1c46b965734ebfdf948befe6543bce20/node_modules/@better-auth/core/db/adapter`

You would install:

- `@better-auth/core`
- `@better-auth/utils`
- `@better-fetch/fetch`

In his case, all he needed to install was `@better-auth/core`, so you might just need to install whatever package appears first. Anyways, make sure the versions you are installing match up with whatever version is expected by the package importing it, and remember that you should install whatever packages appear in your own error messages, because it's not going to always be the same between projects.

@chandlj hopefully this helps you until the issue is resolved.

**Comment by chandlj** [comment]
@sanny-io Thanks for the detailed reply! Unfortunately, this did not fix the issue in my case. 

For me, I specifically have the following 4 type errors:

- `../../../node_modules/.pnpm/@better-auth+core@1.4.0-beta.21_@better-auth+utils@0.3.0_@better-fetch+fetch@1.1.18_bet_7022cd786dbb2390cc096c41f7e74fe4/node_modules/@better-auth/core/dist/index-DX7czw7K.mjs`.
- `../../../node_modules/.pnpm/better-call@1.0.26/node_modules/better-call/dist/router-BH6Wndse`
- `../node_modules/better-auth/dist/index-6ni7_s3n.mjs`
- `../node_modules/better-auth/dist/index-DdIAwzpJ.mjs`

The only thing that has consistently worked has been turning off `declarations` in my `tsconfig.json`. I have tried installing the individuals packages as you mentioned as well as manually typecasting with `as ReturnType<typeof betterAuth<typeof config>>` which also did not work. If you have other suggestions for how to fix this, that would be great.

Regardless, I do think that this issue should be reopened as 1.4.xx does not fix it.

**Comment by firxworx** [comment]
@himself65 as you can see from the commenters its not fixed.

CC @Bekacru (and thank-you for creating better-auth)

When I wrote the issue I worded it as a _systemic_ type issue for a reason: I proposed it to be an issue to "catch all" the stream of extremely related type issues that devs are experiencing.

I was hoping that highlighting that the cluster of related recurring "spot" type issues appear to be _symptoms_ of a greater common issue would help draw your team's attention to it.

Type issues appearing and disappearing even between patch versions _is the core issue_.

The whack-a-mole "fixes" from version to version are _not_ addressing the underlying causes of this and focusing on what fixes one spot issue appears to lead to other spot issues.

A true fix may involve considering the collective  `better-*`  packages and how they relate to each other, who is the source of what truth, and how they get versioned together.

Please re-open this issue.

----

Only half-joking: I can _smell_ a PM somewhere. 

I know its not y'all. Please pull 'em aside or go above em LOL. 

- your internal projects will likely be impacted as you aim to commercialize and scale your paid offerings
- those hit hardest by this issue are perhaps your target customers for paid offerings: those working on larger and more complex apps in monorepos (devs with budgets)
- headaches with bumping minor or even patch versions is a concern for a auth/security minded library where its often a good practice to keep up-to-date as security issues get fixed
- developer pain conflicts with better auth's stated goals and _raison d'être_

Perhaps a few hours of a next-level consulting TypeScript wizard's efforts could help sort through without impacting team velocity. Congrats on the funding, yay for a use for it!

I truly appreciate the work you put into better-auth and I believe it is destined for great things!

**Comment by himself65** [comment]
Do you have repo so I can reproduce?

**Comment by chandlj** [comment]
@himself65 I can't give you mine (proprietary) but I can give you rough instructions to reproduce:

1. Make a shadcn monorepo with Next.js: https://ui.shadcn.com/docs/monorepo
2. Add better-auth and drizzle (not sure how important this is but this is just what I have) to the Next.js package
3. Attempt to create `auth.ts` and view the error.

Hopefully this is enough to reproduce, if you don't see it let me know

**Comment by firxworx** [comment]
@himself65 thank-you for reopening, hugely appreciated :) 

I don't have a good repo handy to share though I may have time later this week. 

In the meantime, looking at the issues and the recurring "whack a mole" problem that spans across many configurations and plugins, I would propose a purpose-built "type issue detector" monorepo to shine a light on this.

I'd suggest using pnpm because its very anal about dependencies and use ESM. Plus there's nice at-a-glance feedback of the "web" of dependent `better-*` packages and versions at play in Intellisense for any given issue e.g. see @sanny-io comment above.

**Use `syncpack`**

As you play with dependency versions `syncpack` helps ensure they mutually agree with each other across different apps/packages in your workspace to provide confidence you aren't introducing issues of your own specific to the workspace vs. better-auth.

**Test Auth Packages**

Add a bunch of discrete auth packages to isolate the dependencies e.g. `@workspace/auth-with-drizzle-sqlite` under `packages/auth-with-drizzle-sqlite`.

For each test package define and export a better-auth `auth` instance (and/or a factory that returns it) plus type definitions that are inferred from the instance and/or its configuration object. Do not use any `as` casts or other type cheats.

I think you'd want to cover a bunch of cases e.g.

- `auth-with-drizzle-sqlite.ts`
- `auth-with-organization-plugin.ts`
- etc.

Plus perhaps a few kitchen sink configurations that replicate popular combinations of features and plugins, inspired from all the different issues and commenters of the past and their affected configurations.

- Ensure the packages define exports properly
- Add a typecheck script using `tsc`

It is pretty much guaranteed at this point that you will find cases where type checks fail.

Remember to ensure your IDE e.g. VSCode is configured to use the workspace "package version" of TypeScript so you can see the issues properly in your editor and so it agrees with `tsc` results: `"typescript.tsdk": "node_modules/typescript/lib"`. 

**Test Dependents**

To go the full 9 yards, you could add an app/package or two that have an auth package as a dependency and have a module where you import and use the auth instance.

To get good detection you could ensure you make use of or reference the types/properties that would be conditionally impacted by the particular configuration being tested.

The idea is you could see how type checks fail or see first hand how the consuming app/packages can have issues resolving types.

You could use purpose-built type testing packages to confirm expected equivalencies however I don't think they're necessary.

**Comment by mimamuh** [comment]
I'm getting similar issues with `1.4.2`. 

@himself65: I've made a repro to reproduce the issue here: [bug-exaple-better-auth-1_4_2](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2)

This reproduction is based on [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) where I did nothing but only upgraded better-auth to `1.4.2` and now [get the lint errors](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2/actions/runs/19716892273/job/56491029889#step:5:72): 
```
The inferred type of 'XXX' cannot be named without a reference to 'XXXX.mjs'. This is likely not portable. A type annotation is necessary. ts(2742)
```

---
### To reproduce:
1. Clone repro [bug-exaple-better-auth-1_4_2](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2) and `cd` into it
2. Install dependencies using `pnpm install`
3. Run `pnpm run lint` for seeing the issues

**Comment by zigcccc** [comment]
☝️ just tested and it happens with version `1.4.3` too

**Comment by joeyorlando** [comment]
@himself65 this is honestly preventing us from upgrading beyond `1.4.1` 🙁

**Comment by jofflin** [comment]
Same for us. We are stuck with 1.3.33, we tried each version and running into issues

**Comment by himself65** [comment]
Thanks, I'm checking rn

**Comment by Bekacru** [comment]
Hey @mimamuh i've been trying to reproduce your issue using the repo you peovider

it only fails if I do pnpm lint globally and other than that, it doesn't break on the editor or when running lint on each package. Can you guys please let me know more aobut your setup and exact issues your facing? @joeyorlando @zigcccc @jofflin

**Comment by joeyorlando** [comment]
@himself65 @Bekacru I posted some detailed repro instructions on Discord [here](https://discordapp.com/channels/1288403910284935179/1445542747489698022/1445555787304009930) for how we use/configure better-auth over in https://github.com/archestra-ai/archestra

**Comment by himself65** [comment]
Just 

> I'm getting similar issues with `1.4.2`.
> 
> [@himself65](https://github.com/himself65): I've made a repro to reproduce the issue here: [bug-exaple-better-auth-1_4_2](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2)
> 
> This reproduction is based on [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) where I did nothing but only upgraded better-auth to `1.4.2` and now [get the lint errors](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2/actions/runs/19716892273/job/56491029889#step:5:72):
> 
> ```
> The inferred type of 'XXX' cannot be named without a reference to 'XXXX.mjs'. This is likely not portable. A type annotation is necessary. ts(2742)
> ```
> 
> ### To reproduce:
> 1. Clone repro [bug-exaple-better-auth-1_4_2](https://github.com/mimamuh/bug-exaple-better-auth-1_4_2) and `cd` into it
> 2. Install dependencies using `pnpm install`
> 3. Run `pnpm run lint` for seeing the issues

I fixed this issue. seems like we miss export one type from the code

**Comment by himself65** [comment]
> [@himself65](https://github.com/himself65) [@Bekacru](https://github.com/Bekacru) I posted some detailed repro instructions on Discord [here](https://discordapp.com/channels/1288403910284935179/1445542747489698022/1445555787304009930) for how we use/configure better-auth over in https://github.com/archestra-ai/archestra

I'm checking this

**Comment by chandlj** [comment]
@himself65 @Bekacru I created a repo here reproducing the error I'm seeing: https://github.com/chandlj/better-auth-test

The steps I took were:
```
pnpm dlx shadcn@latest init # Select the monorepo option
cd apps/web
pnpm add better-auth
```
Please take a look at `apps/web/lib/auth.ts` and you should see the error. Please let me know if you don't! I just did this with `better-auth@1.4.5`

**Comment by himself65** [comment]
> [@himself65](https://github.com/himself65) [@Bekacru](https://github.com/Bekacru) I created a repo here reproducing the error I'm seeing: https://github.com/chandlj/better-auth-test
> 
> The steps I took were:
> 
> ```
> pnpm dlx shadcn@latest init # Select the monorepo option
> cd apps/web
> pnpm add better-auth
> ```
> 
> Please take a look at `apps/web/lib/auth.ts` and you should see the error. Please let me know if you don't! I just did this with `better-auth@1.4.5`

Where is it?

**Comment by chandlj** [comment]
@himself65 sorry thought it was public. Should be fixed now

**Comment by joeyorlando** [comment]
I just tried upgrading to `1.4.6-beta.3` and I still get this.

however one thing I noticed is that in my plugins array if I comment out the `apiKey` plugin ([here](https://github.com/archestra-ai/archestra/blob/main/platform/backend/src/auth/better-auth.ts#L112)), the type errors on `auth` go away 🤔  (but of course cause type errors elsewhere related to `auth.api.verifyApiKey` references)

(more context in Discord thread [here](https://discord.com/channels/1288403910284935179/1445542747489698022/1446947422503698505))

**Comment by picardplaisimond** [comment]
> I just tried upgrading to `1.4.6-beta.3` and I still get this.
> 
> however one thing I noticed is that in my plugins array if I comment out the `apiKey` plugin ([here](https://github.com/archestra-ai/archestra/blob/main/platform/backend/src/auth/better-auth.ts#L112)), the type errors on `auth` go away 🤔 (but of course cause type errors elsewhere related to `auth.api.verifyApiKey` references)
> 
> (more context in Discord thread [here](https://discord.com/channels/1288403910284935179/1445542747489698022/1446947422503698505))

Same thing happens to me when I remove the Stripe Plugin... hmmm.

**EDIT: Updated from 1.4.5 to 1.4.7, and the error is gone (for now...)**

**Comment by marcmaceira** [comment]
> Same thing happens to me when I remove the Stripe Plugin... hmmm.
> 
> **EDIT: Updated from 1.4.5 to 1.4.7, and the error is gone (for now...)**

I still have the error on 1.4.7 😅

**Comment by f1shy-dev** [comment]
i have it on 1.4.9 :(

> The inferred type of 'createAuth' cannot be named without a reference to '../../node_modules/better-auth/dist/plugins/anonymous/types.mjs'. This is likely not portable. A type annotation is necessary.

**Comment by ktisakib** [comment]
1.4.17 the error reappeared

**Comment by joeyorlando** [comment]
my two-cents - I think this should be prioritized, the dev-ex on this is not great (you end up having to type your `betterAuth` instance as such 🙁

```ts
export const auth: any = betterAuth({
  ...
```

**Comment by fierysolid** [comment]
I was able to get 1.5.4 working with the following overrides:
```
  "pnpm": {
    "overrides": {
      "better-auth": "1.5.4",
      "better-call": "1.3.2",
      "@better-auth/core": "1.5.4",
      "@better-auth/sso": "1.5.4",
      "@better-fetch/fetch": "1.1.21",
...
```

**Comment by gBasil** [comment]
Hi, this remains an issue. Here's a minimal reproduction for `better-auth` `1.6.26`, with the `@better-auth/api-key` plugin:
https://github.com/gBasil/REPRO-better-auth

The following error is printed when trying to build the repository:
```
pnpm build:tsc

> auth-test@1.0.0 build:tsc /dir/auth-test
> tsc

src/index.ts:4:17 - error TS2883: The inferred type of 'initAuth' cannot be named without a reference to '$strip' from '.pnpm/zod@4.4.3/node_modules/zod/v4/core'. This is likely not portable. A type annotation is necessary.

4 export function initAuth() {
                  ~~~~~~~~


Found 1 error in src/index.ts:4

 ELIFECYCLE  Command failed with exit code 1.
```

Can this issue be re-opened? And given that this is an issue that keeps popping up version after version, it might be good to disable automatically marking it as stale until it's solved for good, if possible.
